version: '3'

services:
  api:
    volumes:
      - "./src/php-profile-rest-api:/var/www/html"
  frontend_app:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src/react_frontend:/app
    entrypoint:
      - "npm"
      - "start"
